version: '3.8'
services:
 worker-1:
   container_name: worker-1
   image: amd64/ubuntu
   restart: always
   ports:
     - "10250:10250"
     - "30000:32767:30000:32767"
   networks:
     - worker-node

 worker-2:
   container_name: worker-2
   image: amd64/ubuntu
   restart: always
   ports:
     - "10250:10250"
     - "30000:32767:30000:32767"
   networks:
     - worker-node
     
 worker-3:
   container_name: worker-3
   image: amd64/ubuntu
   restart: always
   ports:
     - "10250:10250"
     - "30000:32767:30000:32767"
   networks:
     - worker-node

networks:
 worker-node: